# Generated by Django 5.0.6 on 2024-05-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='nombreAlumno',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='nombre',
            new_name='nombreAsignatura',
        ),
    ]
