# Generated by Django 5.0.6 on 2024-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasApp', '0002_rename_nombre_alumno_nombrealumno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='nombreAlumno',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='nombreAsignatura',
            new_name='nombre',
        ),
    ]
